build_and_install_all: use pacman --ask=4 instead of expect
pacman implements option --ask=4 to automatically answer yes to a
question like:

    Error: pambase-selinux and pambase are in conflict. Remove pambase? [y/N]

Use this undocumented option instead of a racy expect loop which may
cause issues when the pacman command is too slow (c.f.
https://github.com/archlinuxhardened/selinux/issues/11).